package de.htwg.cad.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Set;

@Data
@DynamoDBTable(tableName = "project")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Project {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String createdAt;

    @DynamoDBAttribute
    private Set<String> members;
}
