package de.htwg.cad.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Set;

@Data
@DynamoDBTable(tableName = "work")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Work {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String date;

    @DynamoDBTypeConvertedJson
    private Set<WorkPackage> workPackages;
}
