apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: time-tracker-backend-cluster
  region: eu-central-1

vpc:
  id: vpc-0f02b2b3ba975f91d
  cidr: 192.168.0.0/16
  subnets:
    public:
      eu-central-1a:
        id: subnet-08d264ccc331fe24c
      eu-central-1b:
        id: subnet-0d0e6a04e71c2ddd3
    private:
      eu-central-1a:
        id: subnet-078c09c4054424fed
      eu-central-1b:
        id: subnet-0011d00286f19a430

nodeGroups:
  - name: EKS-public-workers
    instanceType: t3.small
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t3.small
    desiredCapacity: 1
    privateNetworking: true
