apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: time-tracker-backend-cluster
  region: eu-central-1

vpc:
  id: vpc-0f6daeb4ad1c716ea
  cidr: 192.168.0.0/16
  subnets:
    public:
      eu-central-1a:
        id: subnet-07c38dceedea4ae30
      eu-central-1b:
        id: subnet-01e2c05702dac2abc
    private:
      eu-central-1a:
        id: subnet-069062111560db2f9
      eu-central-1b:
        id: subnet-079e76e8a22b37d01

nodeGroups:
  - name: EKS-public-workers
    instanceType: t3.small
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t3.small
    desiredCapacity: 1
    privateNetworking: true
