apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: time-tracker-backend-cluster
  region: eu-central-1

vpc:
  id: vpc-043e3b28a9e44bea6
  cidr: 192.168.0.0/16
  subnets:
    public:
      eu-central-1a:
        id: subnet-0a8cda0417432be43
      eu-central-1b:
        id: subnet-01bbb51887248043b
    private:
      eu-central-1a:
        id: subnet-07a938dfda0d9bdef
      eu-central-1b:
        id: subnet-0ae764e94a7acf1c4

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.micro
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true
