apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: time-tracker-backend-cluster
  region: eu-central-1

vpc:
  id: vpc-022b81c5a4eff064f
  cidr: 192.168.0.0/16
  subnets:
    public:
      eu-central-1a:
        id: subnet-0fda8b4e27a568c30
      eu-central-1b:
        id: subnet-03e8ae507b1b4b456
    private:
      eu-central-1a:
        id: subnet-0680d69f272d3f20a
      eu-central-1b:
        id: subnet-0456d3c7546f5dc01

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.micro
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true
