apiVersion: v1
kind: Service

metadata:
  name: time-tracker-microservice-service

spec:
  type: NodePort
  selector:
    app: time-tracker-microservice
  ports:
    -  port: 8082 # port of this service (cluster members talk via this port)
       targetPort: 8082 # where container is actually running
